version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      # specify the version you desire here
      - image:  circleci/node:latest-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --network-timeout 1000000
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: runing server
          command: yarn start
          background: true


      # run tests!
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: CI=true yarn test --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "coverage/js-tests-results.xml"
      - store_test_results:
          path: coverage