name: CI
on:
  pull_request:
jobs:
    E2E:
      timeout-minutes: 60
      name: E2E Testing
      runs-on: ubuntu-latest
      steps:
        - name: Install Playwright
          run: yarn create playwright

        - name: Waiting for 200 from the Netlify Preview
          uses: jakepartusch/wait-for-netlify-action@v1.2
          id: waitFor200
          with:
            site_name: "builder69"
            max_timeout: 360 # 6 Minu

        - name: Run E2E Tests on Netlify URL
          run: yarn test:e2e
          env:
            PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
