name: CI
on:
  pull_request
jobs:
    install:
        name: Install 🧶
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
          - name: 🛑 Cancel Previous Runs
            uses: styfle/cancel-workflow-action@0.10.0

          - name: Checkout
            uses: actions/checkout@v3
            with:
                token: ${{ secrets.GIT_TOKEN || github.token  }}

          - name: Get yarn cache directory path
            id: yarn-cache-dir-path
            run: echo "::set-output name=dir::$(yarn cache dir)"

          - name: Cache yarn files
            uses: actions/cache@v3
            id: yarn-cache-files
            with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-files-${{ hashFiles('**/yarn.lock') }}
                restore-keys: ${{ runner.os }}-yarn-files-

          - name: Setup yarn access
            run: |
                git config --global url."https://${{ secrets.GIT_TOKEN || github.token  }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
                sed -i "s|Builder/|git+https://github.com/Money-Flow/|" package.json
          - name: Install JS dependencies
            run: yarn install

          - name: Pack artifact
            run: tar czf /tmp/artifact.tar.gz .

          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
                name: frontend-artifact
                path: /tmp/artifact.tar.gz
                retention-days: 1

    chromatic-deployment:
      name: Chromatic Deployment 📗
      runs-on: ubuntu-latest
      steps:
        - name: 🛑 Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.10.0

        - name: Checkout
          uses: actions/checkout@v3

        # It's not working with frontend-artifact, need investigate'
        - name: Install 🧶
          run: yarn

        - name: Publish to Chromatic 📗
          uses: chromaui/action@v1
          with:
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

    eslint:
      name: Eslint 🤡
      needs: [install]
      runs-on: ubuntu-latest
      continue-on-error: false
      steps:
          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
                name: frontend-artifact

          - name: Unpack artifact
            run: tar xf artifact.tar.gz

          - name: Setup problem matcher for eslint
            run: echo "::add-matcher::.github/configs/eslint-matcher.json"

          - name: Run eslint
            run: yarn eslint

    stylelint:
      name: Stylelint 💅
      needs: [install]
      runs-on: ubuntu-latest
      continue-on-error: false
      steps:
          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
                name: frontend-artifact

          - name: Unpack artifact
            run: tar xf artifact.tar.gz

          - name: Run stylelint
            run: yarn stylelint

    typescript:
        name: Typescript 🎪
        needs: [install]
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: frontend-artifact

            - name: Unpack artifact
              run: tar xf artifact.tar.gz

            - name: Run typescript compile
              run: yarn tsc --noEmit

    tests:
      name: Unit tests 🧪
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - name: 🛑 Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.10.0

        - name: Checkout
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GIT_TOKEN || github.token  }}

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
              name: frontend-artifact

        - name: Unpack artifact
          run: tar xf artifact.tar.gz

        - name: Testing 🧪
          run: yarn test

    deploy-preview:
      name: Deploy Preview 🚀
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - name: 🛑 Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.10.0

        - name: Checkout
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GIT_TOKEN || github.token  }}

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
              name: frontend-artifact

        - name: Unpack artifact
          run: tar xf artifact.tar.gz

        - name: Build TS application
          run: yarn build

        - name: Deploy to Netlify
          uses: nwtgck/actions-netlify@v1.2
          id: deploy-to-netlify
          with:
            publish-dir: './build'
            production-branch: master
            production-deploy: false
            github-token: ${{ secrets.GITHUB_TOKEN }}
            deploy-message: "Deploy to Netlify from GitHub Actions"
            enable-pull-request-comment: false
            enable-commit-comment: false
            overwrites-pull-request-comment: false
            github-deployment-environment: 'deploy-preview'
            alias: deploy-preview-${{ github.event.number }}
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    # E2E:
    #   name: Playwright 🧪
    #   needs: [deploy-preview]
    #   runs-on: ubuntu-latest
    #   timeout-minutes: 60
    #   steps:
    #     - name: 🛑 Cancel Previous Runs
    #       uses: styfle/cancel-workflow-action@0.10.0

    #     - name: Checkout
    #       uses: actions/checkout@v3
    #       with:
    #         token: ${{ secrets.GIT_TOKEN || github.token  }}

    #     - name: Download artifact
    #       uses: actions/download-artifact@v3
    #       with:
    #           name: frontend-artifact

    #     - name: Unpack artifact
    #       run: tar xf artifact.tar.gz

    #     - name: Install Playwright
    #       # run: npm install @playwright/test && npx playwright install

    #     - name: Run E2E Tests on Netlify URL 🧪
    #       # run: yarn test:e2e
    #       env:
    #         PLAYWRIGHT_TEST_BASE_URL: https://deploy-preview-${{ github.event.number }}--cash69.netlify.app
